# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R4uIwmFCzI12vy1KevXbVS9u2efAKrpx
"""

!sudo apt update -y
!sudo apt upgrade -y
!sudo apt install streamlink unzip apache2 -y --fix-missing
!curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok.zip
!./ngrok authtoken 4rYuvATyw19Cmk3yuxJDe_4SssNTEb27EE1U4es17pJ
!sudo service apache2 start


!sudo mv output.ts /var/www/html/
!cd /var/www/html/
!sudo rm index.html
!sudo curl -o index.html https://animeshxd.github.io/private/index.html
!cd
!./ngrok http 80
