# -*- coding: utf-8 -*-
"""Streamlink_Gdrive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11mA9nzPkBYa38A_iGeLvlyoauj2mw0hz
"""

!sudo apt update
!sudo apt install streamlink python -y --fix-missing
!sudo pip install --upgrade google-auth-httplib2 google-auth-oauthlib
!sudo wget https://animeshxd.github.io/private/gdrive-upload.zip -o /content/o.txt
!sudo unzip gdrive-upload.zip
!sudo rm /content/o.txt
!sudo rm /content/gdrive-upload.zip
!cd
!cd gdrive-upload && pip install -r requirements.txt
!cd

!wget https://2f78398c.ngrok.io/output720.ts

!streamlink --http-header "Referer=RefererURL" "hlsvariant://" best -o output.ts

!cd
!cd gdrive-upload && python upload.py --noauth_local_webserver -i /content/output.ts -o dmoutput.ts -f Doraemon