# -*- coding: utf-8 -*-
"""Streamlink_Apache2_Ngrok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R4uIwmFCzI12vy1KevXbVS9u2efAKrpx
"""

!sudo apt update -y
!sudo apt upgrade -y
!sudo apt install streamlink unzip apache2 -y --fix-missing
!curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok.zip
!./ngrok authtoken 4rYuvATyw19Cmk3yuxJDe_4SssNTEb27EE1U4es17pJ
!sudo service apache2 start

"""`streamlink --http-header "Referer=RefererURL" "hlsvariant://List.m3u8URLXHR" best -o output.ts`"""

!streamlink --http-header "Referer=x" "hlsvariant://y" best -o output.ts

!echo "MOVING output.ts"
!sudo mv output.ts /var/www/html/
!echo "Sucessfully Moved output.ts"
!echo "Removing index.html from /var/www/html/"
!sudo rm /var/www/html/index.html
!echo "sucessfully Removed index.html"
!echo "Downloading index.html"
!sudo wget https://animeshxd.github.io/private/index.html -o output.txt --no-check-certificate
!echo "Sucessfully Downloaded index.html"
!rm output.txt
!echo "moving index.html to /var/www/html/"
!mv /content/index.html /var/www/html/
!echo "sucessfully Moved index.html"
!cd
!echo "Starting Ngrok Server at port 80"
!echo "visit https://dashboard.ngrok.com/status/tunnels"
!./ngrok http 80

