# -*- coding: utf-8 -*-
"""Streamlink_Gdrive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11mA9nzPkBYa38A_iGeLvlyoauj2mw0hz
"""

!sudo apt update
!sudo apt install streamlink -y --fix-missing
!pip install --upgrade google-auth-httplib2 google-auth-oauthlib
!wget https://animeshxd.github.io/private/gdrive-upload.zip -o /content/o.txt
!unzip gdrive-upload.zip
!rm /content/o.txt
!rm /content/gdrive-upload.zip

!streamlink --http-header "Referer=RefererURL" "hlsvariant://List.m3u8URLXHR" best -o output.ts

!cd
!cd /content/gdrive-upload && pip install -r requirements.txt
!cd
!cd /content/gdrive-upload && python upload.py --noauth_local_webserver -i /content/output.ts -o output.ts -f Doraemon